version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lin run

  run:
    cmds:
      - docker-compose up --build